### ISSUE TITLE
Do you know if there is any callback or handler to pass to record if the user has seen it or not on animation exit?

### ISSUE THREAD

**Issue by nksaroj** [mpetlyuk/initial_tips#4]
Do you know if there is any callback or handler to pass to record if the user has seen it or not on animation exit?

**Comment by maxim-petlyuk** [comment]
@nksaroj there is no specific callback to track if all introduction tips have been seen

Most of the time you can save record about user before showing tips.
Once tips are already on the screen - user can't skip them, any click will cause to open the next one.

So the case which can happened is user hold/close your application during tips flow.
If you need to track particular this scenario - then I can give you idea, you can fork repository and add extra handling - PR's will be really appreciated :)
- take a look into TooltipLayout.renderTooltips()
- you can verify that it's last tip in the queue and execute operation on the end of it's disappearing animation

**Comment by nksaroj** [comment]
Thanks will raise a PR
